# LA 10 - Inverse Kinematics for a Simplified Industrial Robot

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH
rtd = 180/pi
dtr = pi/180

## Schemiatic for a Simplified Industrial Robot (SIR-bot)


<img src="https://faculty.gvsu.edu/kraussry/445_images/learning_activities/inverse_kin_sketches/simplified_industrial_robot.png" width=500px>


## Given

In [4]:
T0tip = np.array([[ 0.03711078,  0.16963632,  0.98480775, 19.13931916],
       [-0.21046567, -0.96205536,  0.17364818,  3.37477836],
       [ 0.97689661, -0.21371244,  0.        , 15.99040766],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
T0tip

array([[ 0.03711078,  0.16963632,  0.98480775, 19.13931916],
       [-0.21046567, -0.96205536,  0.17364818,  3.37477836],
       [ 0.97689661, -0.21371244,  0.        , 15.99040766],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

### Parameters

In [12]:
A = 9
B = 7
C = 6
D = 5
E = 4

## Step 1: $^0P_{wrist}$

Use matric math to find the wrist location in frame 0.

So that you can check your answer, the answer is:

$$^0P_{wrist} \textrm{:}$$



In [45]:
P_wrist_0_check = np.array([10.27604938,  1.81194476, 15.99040766])
P_wrist_0_check

array([10.27604938,  1.81194476, 15.99040766])

## Step 2: Find $\theta_1$ and $^1P_{wrist}$

Next, find $\theta_1$ based on a top view.  Once you know $\theta_1$, find the wrist location in frame 1 so that you could draw a side view and solve the two link inverse kinematics problem to find $\theta_2$ and $\theta_3$.

So that you can check your answer, $^1P_{wrist}$:

In [46]:
P_wrist_1_check = np.array([10.434574  ,  0.        ,  6.99040766])
P_wrist_1_check

array([10.434574  ,  0.        ,  6.99040766])

## Step 3: Find $\theta_2$ and $\theta_3$ from a side view in frame 1

## Step 3: Find $^0_{W}\mathbf{T}$

Based on $\theta_1$, $\theta_2$, and $\theta_3$, find $^0_{wrist}\mathbf{T}$:

$$^0_{W}\mathbf{T} = \; ^0_1\mathbf{T} \cdot  ^1_2\mathbf{T} \cdot ^2_3\mathbf{T} \cdot ^3_W\mathbf{T}$$

## Step 4: Find $^W_{tip}\mathbf{T}_{numeric}$

$$^0_{tip}\mathbf{T} = \; ^0_W \mathbf{T} \cdot ^W_{tip}\mathbf{T}$$

## Step 5: Find $^W_{tip}\mathbf{T}_{symbolic}$

Use symbolic forward kinematics to find $^W_{tip}\mathbf{T}_{symbolic}$

## Step 6: Solve for $\theta_4$ and $\theta_5$

Setting

$$^W_{tip}\mathbf{T}_{numeric} = \; ^W_{tip}\mathbf{T}_{symbolic}$$

gives you 12 equations to work with.  Choose a subset of those equations that allow you 
to solve for $\theta_4$ and $\theta_5$.

## Step 7: Final Verification

Now that you have answers for all of the joint angles, use a DH table and forward kinematics to find $^0_{tip}\mathbf{T}$ and verify that it matches the one given in the problem statement.