# Learning Activity 4: Introduction to HT Matrices

In [14]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import copy
import robotics
from robotics import Rx, HTz, Rz, cosd, sind, HTx

dtr = np.pi/180

In [15]:
robotics.HTz

<function robotics.HTz(angle=0, x=0.0, y=0.0, z=0.0)>

In [16]:
HTz

<function robotics.HTz(angle=0, x=0.0, y=0.0, z=0.0)>

In [26]:
def myarraytest(in1, in2):
    mydiff = np.array(in1) - np.array(in2)
    mymax = np.max(np.abs(mydiff))
    return mymax < 1e-6

## robotics.HTz

In [27]:
help(robotics.HTz)

Help on function HTz in module robotics:

HTz(angle=0, x=0.0, y=0.0, z=0.0)



- `angle` is the rotation about the Z axis in degrees
- `x`, `y`, and `z` are the elements of $^AP_{BORG}$

In [28]:
robotics.HTz(30,1,2,3)

array([[ 0.8660254, -0.5      ,  0.       ,  1.       ],
       [ 0.5      ,  0.8660254,  0.       ,  2.       ],
       [ 0.       ,  0.       ,  1.       ,  3.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [29]:
T01 = HTz(30,1,0,0)
T01

array([[ 0.8660254, -0.5      ,  0.       ,  1.       ],
       [ 0.5      ,  0.8660254,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  1.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [30]:
T12 = HTx(90,0,0,0)

In [31]:
T23 = HTz(-60,1,2,3)

## Python code: `prettymat` and `dot_list`

$$^0_3\mathbf{T} = \; ^0_1\mathbf{T} \cdot ^1_2\mathbf{T} \cdot ^2_3\mathbf{T}$$

In [32]:
robotics.prettymat(robotics.dot_list([T01,T12,T23]))

array([[ 0.4330127 ,  0.75      ,  0.5       ,  3.3660254 ],
       [ 0.25      ,  0.4330127 , -0.8660254 , -2.09807621],
       [-0.8660254 ,  0.5       ,  0.        ,  2.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

#### Painful alternative

- what does `dot_list` do?

In [33]:
robotics.prettymat(np.dot(T01,np.dot(T12,T23)))

array([[ 0.4330127 ,  0.75      ,  0.5       ,  3.3660254 ],
       [ 0.25      ,  0.4330127 , -0.8660254 , -2.09807621],
       [-0.8660254 ,  0.5       ,  0.        ,  2.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

## Problem 1: Displacement Only Example

<img src="https://faculty.gvsu.edu/kraussry/445_images/learning_activities/intro_to_HT/intro_to_HT_1.png" width=600px>

### Given

$^BP_1$ :

In [34]:
P_B1 = np.array([1,3,0,1])
P_B1

array([1, 3, 0, 1])

### Find

- $^A_B\mathbf{T}_1$

and

- $^AP_1$

Your code must define `T_AB1` and `P_A1`.

### Tests

In [39]:
assert myarraytest(P_A1[0:3],[5., 5., 0])
assert T_AB1.shape == (4,4)
print("success")

# Problem 2: Numeric Example 1

<img src="https://faculty.gvsu.edu/kraussry/445_images/learning_activities/intro_to_HT/intro_to_HT_2.png" width=600px>

### Adding Vectors

- we are still adding vectors head to tail, but the vectors must be in the same frame before we add them

- Find $^A_B\mathbf{T}_2$ using `robotics.HTz`
   - prove that your `T_AB2` is correct
- Find $^AP$ and verify by inspection that your answer is reasonable

### Tests

In [1]:
assert myarraytest(P_A2[0:3],[4+3*cosd(30), 2+3*sind(30), 0])
assert T_AB2.shape == (4,4)
print("success")

NameError: name 'myarraytest' is not defined

## Problem 3: Numeric Example 2

<img src="https://faculty.gvsu.edu/kraussry/445_images/learning_activities/intro_to_HT/intro_to_HT_3.png" width=600px>

### Problem statement

- Find `T_AB3`, `Q_B3` and `PB3` and use them to calculate `P_A3` and `Q_A3`  

### Tests

In [2]:
assert myarraytest(P_A3[0:3],[4.,6.,0.])
assert myarraytest(Q_A3[0:3],[2.,3.,0.])
assert T_AB3.shape == (4,4)
print("success")

NameError: name 'myarraytest' is not defined

## Problem 4: Two Link Robot Example

<img src="https://faculty.gvsu.edu/kraussry/445_images/learning_activities/intro_to_HT/intro_to_HT_4.png" width=600px>

If $L_1$ = 10cm, $L_2$ = 8cm, $\theta_1$ = 25$^\circ$, and $\theta_2$ = 35$^\circ$, find $^0P_{tip}$.

- find the answer using HT matrices 
- verify your answer based on trig

Be sure to define the variable `P_tip0` as your final answer.

$$^0_2\mathbf{T} = \; ^0_1\mathbf{T} \cdot ^1_2\mathbf{T}$$

$$^0P_{tip} = \; ^0_1\mathbf{T} \cdot ^1_2\mathbf{T} \cdot ^2P_{tip}$$

### Test

In [3]:
assert myarraytest(P_tip0[0:3],[13.06307787,11.15438585,0.])
print("success")

NameError: name 'myarraytest' is not defined