# PUMA Inverse Kinematics Wrist Example

## PUMA YouTube Video

If you aren't sure how the PUMA moves or what the schematic needs to capture, watch this video:
[https://youtu.be/ArzP7rh4_9Q](https://youtu.be/ArzP7rh4_9Q)

Here is a link to Dr. Krauss' YouTube video concerning the PVC PUMA model:
[https://youtu.be/lX0cCZkAzrU](https://youtu.be/lX0cCZkAzrU)

In [1]:
def myarraytest(in1, in2):
    mydiff = np.array(in1) - np.array(in2)
    mymax = np.max(np.abs(mydiff))
    return mymax < 1e-6

In [13]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH, HTinv, dot_list, prettymat
rtd = 180/pi
dtr = pi/180

<img src="https://faculty.gvsu.edu/kraussry/445_images/puma/puma_pvc_joint_angles.jpeg" width=300px>

<img src="https://faculty.gvsu.edu/kraussry/445_images/puma/puma_sort_of_top_back.jpeg" width=300px>

<img src="https://faculty.gvsu.edu/kraussry/445_images/puma/puma_weird_schematic.jpeg" width=300px>

<img src="https://faculty.gvsu.edu/kraussry/445_images/puma/puma_pvc_in_schematic_position.jpeg" width=300px>

For the PUMA model above, the following lengths are in inches:

In [3]:
A = 16
B = 9
C = 21
D = 3.5
E = 3
F = 11
G = 5

## Dr. Krauss' PUMA DH Table

i|$\alpha$|$a$|$\theta$|d
-|--------|----|--------|-------------
1|0|0|$\theta_1$|A
2|90|0|$\theta_2$|0
3|0|C|$\theta_3$|D-B
4|90|E|th4|F
5|-90|0|th5|0
6|90|0|th6|G

## Problem Statement

Given the HT matrix $^0_{tip}\mathbf{T}$:

In [15]:
T_0_tip = np.array([[-0.04905994, -0.79720351,  0.60171396, 31.60648245],
       [-0.89714672,  0.29996241,  0.32426889, 12.78315737],
       [-0.43899987, -0.52391709, -0.72992465, 16.36523055],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
T_0_tip

array([[-0.04905994, -0.79720351,  0.60171396, 31.60648245],
       [-0.89714672,  0.29996241,  0.32426889, 12.78315737],
       [-0.43899987, -0.52391709, -0.72992465, 16.36523055],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

### Step 1

First, use the technique outlined in lecture to find the wrist location, $^0P_{wrist}$

In [33]:
P_wrist_0_check = np.array([28.59791263, 11.16181292, 20.01485379])
P_wrist_0_check

array([28.59791263, 11.16181292, 20.01485379])

### Steps 2-N

Assume you found the first three joint angles based on graphical analysis of the top and side views:

In [4]:
th1 = 11
th2 = 22
th3 = 33

- Verify that these three joint angles lead to the correct wrist location $^0P_{wrist}$
- Find $^0_{w}\mathbf{T}$
- Find the joint angles $\theta_4$, $\theta_5$, and $\theta_6$
    - Find $^W_{tip}\mathbf{T}_{num}$
    - Use symbolic forward kinematics to find $^W_{tip}\mathbf{T}_{sym}$
    - Pick out equations to help you find $\theta_4$, $\theta_5$, and $\theta_6$
- Use forward kinematics to verify that you have a valid full solution that leads to $^0_{tip}\mathbf{T}$

## Answers for checking


$^0_{w}\mathbf{T}$:

In [37]:
T_0_wrist_check = np.array([[ 0.56303822,  0.190809  ,  0.80410191, 28.59791263],
       [ 0.10944354, -0.98162718,  0.15630158, 11.16181292],
       [ 0.81915204,  0.        , -0.57357644, 20.01485379],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
T_0_wrist_check

array([[ 0.56303822,  0.190809  ,  0.80410191, 28.59791263],
       [ 0.10944354, -0.98162718,  0.15630158, 11.16181292],
       [ 0.81915204,  0.        , -0.57357644, 20.01485379],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

$^W_{tip}\mathbf{T}_{num}$:

In [40]:
T_wrist_tip_check = np.array([[-0.48541718, -0.84519485, -0.22364217, -1.11821086],
       [ 0.87130253, -0.44656486, -0.20349872, -1.0174936 ],
       [ 0.07212534, -0.29364177,  0.95319067,  4.76595334],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
T_wrist_tip_check

array([[-0.48541718, -0.84519485, -0.22364217, -1.11821086],
       [ 0.87130253, -0.44656486, -0.20349872, -1.0174936 ],
       [ 0.07212534, -0.29364177,  0.95319067,  4.76595334],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])