# Learning Activity 5


In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from numpy import sin, cos, tan, pi
import robotics
from robotics import Rx, Ry, Rz, sind, cosd, DH
rtd = 180/pi
dtr = pi/180

In [3]:
def myarraytest(in1, in2):
    mydiff = np.array(in1) - np.array(in2)
    mymax = np.max(np.abs(mydiff))
    return mymax < 1e-6

## Problem 1

<img src="https://faculty.gvsu.edu/kraussry/445_images/learning_activities/HT_inverse/ht_inverse_1.png" width=400px>

- find $^A_B\mathbf{T}$ and $^B_A\mathbf{T}$


- find $^AP$ and $^BQ$

**Note:** your code must define `T_AB1`, `T_BA1`, `P_A1`, and `Q_B1` for the tests.

### Tests

In [4]:
assert myarraytest(np.dot(T_AB1, T_BA1),np.eye(4))
assert myarraytest(P_A1,[4.8, 6.4, 0.,1])
assert myarraytest(Q_B1,[0.6,-0.8,0.,1.])
print("success")

NameError: name 'T_AB1' is not defined

## Problem 2

$$^A_B\mathbf{T} = \; \begin{bmatrix} -0.1736 & -0.9848 & 0 & -0.8682 \\ 0.9848 & -0.1736 & 0 & 4.924 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

- sketch the frames $A$ and $B$ in relation to one another
- upload your sketch to blackboard

## Problem 3

If you already have 

$$^A_B\mathbf{T} = \; \begin{bmatrix} -0.5 & -0.866 & 0 & 3 \\ 0 & 0 & 1 & 1 \\ -0.866 & 0.5 & 0 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$$

- use Python to find $^B_A\mathbf{R}$, $^BP_{AORG}$, and $^B_A\mathbf{T}$.

In [5]:
T_AB3 = np.array([[-0.5      , -0.8660254,  0.       ,  3.       ],
                 [ 0.       ,  0.       ,  1.       ,  1.       ],
                 [-0.8660254,  0.5      ,  0.       ,  0.       ],
                 [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [6]:
T_AB3

array([[-0.5      , -0.8660254,  0.       ,  3.       ],
       [ 0.       ,  0.       ,  1.       ,  1.       ],
       [-0.8660254,  0.5      ,  0.       ,  0.       ],
       [ 0.       ,  0.       ,  0.       ,  1.       ]])

In [7]:
R_AB3 = T_AB3[0:3,0:3]
R_AB3

array([[-0.5      , -0.8660254,  0.       ],
       [ 0.       ,  0.       ,  1.       ],
       [-0.8660254,  0.5      ,  0.       ]])

In [10]:
T_AB3[0:3,3]

array([3., 1., 0.])

**Note:**

Your code must define `T_BA3` and `P_AorgB3`.

### Tests

In [9]:
assert myarraytest(np.dot(T_AB3, T_BA3),np.eye(4))
assert myarraytest(P_AorgB3,[ 1.5,2.5980762, -1.])
print("success")

NameError: name 'T_BA3' is not defined